### ISSUE TITLE
AAC with ID3 tag not supported?

### ISSUE THREAD

**Issue by alf-ytakada** [denivip/osmf-hls-plugin#111]
Hi @dangerden !
Does this plugin supports stream that aac with id3 tag ?
I tried my HLS server program, but couldn't play stream...
supports only ts files ?

http://tools.ietf.org/html/draft-pantos-http-live-streaming-14#section-3
> Each Elementary Audio Stream segment MUST signal the timestamp of its
   first sample with an ID3 PRIV tag [ID3] at the beginning of the
   segment.  The ID3 PRIV owner identifier MUST be
   "com.apple.streaming.transportStreamTimestamp".  The ID3 payload MUST
   be a 33-bit MPEG-2 Program Elementary Stream timestamp expressed as a
   big-endian eight-octet number, with the upper 31 bits set to zero.
   An Elementary Audio Stream segment without such an ID3 tag can
   trigger playback errors.

thanks.

**Comment by dangerden** [comment]
Hi @alf-ytakada , yes, so far only ts files

**Comment by alf-ytakada** [comment]
Hi @dangerden , I understand. Thank you!
